### ISSUE TITLE
Enhancement: sync subdirectories

### ISSUE THREAD

**Issue by wendli01** [woefe/studip-sync#1]
It would be nice if you could choose which subdirectory to sync for a course, especially for courses that have supplementary material folders with >100mb.

**Comment by woefe** [comment]
Should be doable. But you'll have to find/copy the IDs of subdirectories manually. The course configuration could look like this:
```json
{
    "course_id": "3dcb76de95b5d8148de3cb72340ade55",
    "save_as": "Computer Networks and Energy Systems",
    "sync_only": ["daad713cca2f27a0f022c34d84d3c605", "141a4c2ac3bd5b9f8321355192feead8"]
},
```
The `sync_only` parameter will be optional and holds a list of the folder IDs to sync. What do you think? Do you like this solution?

**Comment by wendli01** [comment]
Yes, exactly what I wanted :)
